"""Add university column to users

Revision ID: 0e7499c0f47c
Revises: 58ee4135973c
Create Date: 2025-11-11 19:28:54.980876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7499c0f47c'
down_revision: Union[str, None] = '58ee4135973c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('university', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'university')
    # ### end Alembic commands ###
