"""add introduction text field to base user

Revision ID: 343911d63462
Revises: fb386550c4a2
Create Date: 2025-11-13 00:42:37.532353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343911d63462'
down_revision: Union[str, None] = 'fb386550c4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'introduction_text')
    op.add_column('users', sa.Column('introduction_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'introduction_text')
    op.add_column('coaches', sa.Column('introduction_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
