"""add booking system tables

Revision ID: 6dec990c15cb
Revises: c2cefec1fdf3
Create Date: 2025-11-10 23:52:21.142597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dec990c15cb'
down_revision: Union[str, None] = 'c2cefec1fdf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('coacher_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coacher_id'], ['coaches.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coacher_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coacher_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['coacher_id'], ['coaches.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coacher_id', sa.Integer(), nullable=False),
    sa.Column('coacher_availability_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_openslot_time_valid'),
    sa.ForeignKeyConstraint(['coacher_availability_id'], ['coacher_availability.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coacher_id'], ['coaches.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_openslot_search', 'open_slots', ['coacher_id', 'start_at', 'end_at', 'status'], unique=False)
    op.create_table('booking_request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_request_id', sa.Integer(), nullable=False),
    sa.Column('open_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['open_slot_id'], ['open_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_slot_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('booking_item_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('student_feedback', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_session_time_valid'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_session_rating_range'),
    sa.ForeignKeyConstraint(['booking_item_id'], ['booking_request_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coacher_id'], ['coaches.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.account_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('booking_request_items')
    op.drop_index('idx_openslot_search', table_name='open_slots')
    op.drop_table('open_slots')
    op.drop_table('coacher_availability')
    op.drop_table('booking_requests')
    # ### end Alembic commands ###
