"""fix message_requests model

Revision ID: 7ef6ee65b14d
Revises: f3e9345ce749
Create Date: 2025-11-08 19:29:16.239745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef6ee65b14d'
down_revision: Union[str, None] = 'f3e9345ce749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'expired', 'blocked', name='message_request_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('related_conversation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('requester_id <> target_id', name='ck_not_self_request'),
    sa.ForeignKeyConstraint(['handled_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_conversation_id'], ['conversations.conversation_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_requests')
    # ### end Alembic commands ###
