"""gộp user với user_profile

Revision ID: c0066e4a2c7b
Revises: 9d762568eaee
Create Date: 2025-11-08 01:56:49.747976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0066e4a2c7b'
down_revision: Union[str, None] = '9d762568eaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=2000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
