"""thêm  booking_request session,open_slots,coacher_availbility 

Revision ID: c2cefec1fdf3
Revises: 7ef6ee65b14d
Create Date: 2025-11-10 23:49:06.366434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cefec1fdf3'
down_revision: Union[str, None] = '7ef6ee65b14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
