"""Add ondelete=CASCADE to foreign keys

Revision ID: c68d85241f5d
Revises: 0e7499c0f47c
Create Date: 2025-11-11 20:19:03.494450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68d85241f5d'
down_revision: Union[str, None] = '0e7499c0f47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_requests_student_id_fkey', 'booking_requests', type_='foreignkey')
    op.drop_constraint('booking_requests_coacher_id_fkey', 'booking_requests', type_='foreignkey')
    op.create_foreign_key(None, 'booking_requests', 'users', ['coacher_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'booking_requests', 'users', ['student_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_requests', type_='foreignkey')
    op.drop_constraint(None, 'booking_requests', type_='foreignkey')
    op.create_foreign_key('booking_requests_coacher_id_fkey', 'booking_requests', 'users', ['coacher_id'], ['user_id'])
    op.create_foreign_key('booking_requests_student_id_fkey', 'booking_requests', 'users', ['student_id'], ['user_id'])
    # ### end Alembic commands ###
