"""add introduction text field to coach

Revision ID: fb386550c4a2
Revises: 6dec990c15cb
Create Date: 2025-11-13 00:08:02.032101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb386550c4a2'
down_revision: Union[str, None] = '6dec990c15cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('introduction_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'introduction_text')
    # ### end Alembic commands ###
